### ISSUE TITLE
Unhandled promises

### ISSUE THREAD

**Issue by mgor** [johnlemonse/homebridge-telldus#75] opened 2019-05-28 19:14 UTC
Since upgrading to `homebridge@0.4.49` the latest version of this plugin (1.0.5) stopped working:
```
maj 28 21:05:44 pc homebridge[13516]: [5/28/2019, 9:05:44 PM] [Telldus Live] Initializing Telldus platform...
maj 28 21:05:44 pc homebridge[13516]: [5/28/2019, 9:05:44 PM] [Telldus Live] isLocal: false
maj 28 21:05:44 pc homebridge[13516]: [5/28/2019, 9:05:44 PM] [Telldus Live] Loading accessories...
maj 28 21:05:45 pc homebridge[13516]: { sensor: [] }
maj 28 21:05:45 pc homebridge[13516]: [5/28/2019, 9:05:45 PM] [Telldus Live] body used already for: https://api.telldus.com/json/sensors/list
maj 28 21:05:45 pc homebridge[13516]: (node:13516) UnhandledPromiseRejectionWarning: Error: body used already for: https://api.telldus.com/json/sensors/list
maj 28 21:05:45 pc homebridge[13516]:     at Response.Body._decode (/home/user/.local/share/node_modules/lib/node_modules/homebridge-telldus/node_modules/node-fetch/lib/body.js:88:30)
maj 28 21:05:45 pc homebridge[13516]:     at Response.Body.json (/home/user/.local/share/node_modules/lib/node_modules/homebridge-telldus/node_modules/node-fetch/lib/body.js:44:14)
maj 28 21:05:45 pc homebridge[13516]:     at LiveApi.request (/home/user/.local/share/node_modules/lib/node_modules/homebridge-telldus/node_modules/telldus-api/index.js:231:21)
maj 28 21:05:45 pc homebridge[13516]:     at process._tickCallback (internal/process/next_tick.js:68:7)
maj 28 21:05:45 pc homebridge[13516]: (node:13516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
maj 28 21:05:45 pc homebridge[13516]: (node:13516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.
```
Seems like it was a while since anything happened in this repository. If there's no active development, I'll submit a PR when I've had the time to investigate the problem further.

**Comment by mifi** [comment] 2019-06-03 12:39
Hmm, maybe they changed something in the newest version of homebridge. Feel free to investigate and make a PR :)

**Comment by larsamannen** [comment] 2019-06-06 18:12
Getting the following error:
[6/6/2019, 7:57:37 PM] [Telldus Live] request to https://api.telldus.com/json/sensors/list failed, reason: write EPROTO 4403303872:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

(node:36476) UnhandledPromiseRejectionWarning: FetchError: request to https://api.telldus.com/json/sensors/list failed, reason: write EPROTO 4403303872:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-telldus/node_modules/node-fetch/index.js:133:11)
    at ClientRequest.emit (events.js:196:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:196:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:438:5)
    at onwrite (_stream_writable.js:459:5)
    at internal/streams/destroy.js:49:7
    at TLSSocket.Socket._destroy (net.js:593:3)
    at TLSSocket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:84:12)
(node:36476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mifi** [comment] 2019-07-09 19:41
Does it work with older version of homebridge? which version broke it?

**Comment by mgor** [comment] 2019-08-04 18:34
Hm, very strange. I re-arranged my global `node_modules` directory and re-installed `homebridge` and `homebridge-telldus` with npm and the problem disappeared.

**Comment by mifi** [comment] 2019-08-12 13:22
So can close this now?

**Comment by NonjSAme** [comment] 2019-08-16 05:18
I've also hit the same type of problem!

I updated my Rpi to Debian Buster.
And with that came the need to update:
- Node.js to v12.8.0 
- npm to v6.10.3

Now, homebridge had to be updated also. so after completely uninstalled (as far as i can see):
- homebridge-telldus 
- hpmebridge

...and finally all over again a complete new installation of
- homebridge@0.4.50
- homebridge-telldus@1.0.5

I thought it would ready to rock. But unfortunately, even after re-doing the homebridge/homebride-telldus uninstall-install procedure twice, i'm still stuck with the same problem:
`

    pi@SmartHomeServer:~ $ homebridge
    [2019-8-16 5:44:33] Loaded config.json with 0 accessories and 1 platforms.
    [2019-8-16 5:44:33] ---
    [2019-8-16 5:44:33] Loaded plugin: homebridge-telldus
    [2019-8-16 5:44:33] Registering platform 'homebridge-telldus.Telldus'
    [2019-8-16 5:44:33] ---
    [2019-8-16 5:44:33] Loading 1 platforms...
    [2019-8-16 5:44:33] [Telldus Liv!e] Initializing Telldus platform...
    [2019-8-16 5:44:33] [Telldus Liv!e] isLocal: false
    [2019-8-16 5:44:33] [Telldus Liv!e] Loading accessories...
    [2019-8-16 5:44:33] Loading 0 accessories...
    [2019-8-16 5:44:33] [Telldus Liv!e] request to https://api.telldus.com/json/sensors/list failed, reason: write EPROTO 1995573712:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

    (node:1904) UnhandledPromiseRejectionWarning: FetchError: request to https://api.telldus.com/json/sensors/list failed, reason: write EPROTO 1995573712:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1922:

        at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-telldus/node_modules/node-fetch/index.js:133:11)
        at ClientRequest.emit (events.js:203:13)
        at TLSSocket.socketErrorListener (_http_client.js:399:9)
        at TLSSocket.emit (events.js:203:13)
        at errorOrDestroy (internal/streams/destroy.js:107:12)
        at onwriteError (_stream_writable.js:439:5)
        at onwrite (_stream_writable.js:460:5)
        at internal/streams/destroy.js:49:7
        at TLSSocket.Socket._destroy (net.js:595:3)
        at TLSSocket.destroy (internal/streams/destroy.js:37:8)
        at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:84:12)
    (node:1904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
    (node:1904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`
Somewhere on the internet (cant find it again unfortunately) i read that the EPROTO 'unsupported protocol' error could be caused by that - while the minimal supported TLS version in previos versions of Node.js was TLSv1.0 - since v11.4.0, it is raised to TLSv1.2. 
And if there is a certificate being used that is signed with TLSv1.0 this could be the root of the cause. 
But this is way above my knowledge, so if someone more cleaver could comment on this I would be very happy!

**Comment by NonjSAme** [comment] 2019-08-16 10:13
Okay... doing some more tests down the road with the assumption that it might have something to do with TLS-versions. I tried to figure out how to start homebridge with the node flag `--tls-min-v1.0` forcing it to accept TLSv1.0 anyway.

Now, node homebirdge seems to be launched from the homebridge shell script at `/usr/local/lib/node_modules/homebridge/bin`. But adding flags to env in a shebang under Linux seems not as easy. At least not under Debian.

Fortunately , I also stumbled across this site [http://sambal.org/2014/02/passing-options-node-shebang-line/](url)

So, by hard coding `/usr/local/lib/node_modules/homebridge/bin/homebridge` to the following, it actually seems to work!!!!

`

    #!/bin/sh
    ":" //# comment; exec /usr/bin/env node --tls-min-v1.0 "$0" "$@"
    
    console.log('javascript');
    
    //
    // This executable sets up the environment and runs the HomeBridge CLI.
    //
    
    'use strict';
    
    process.title = 'homebridge';
    
    // Find the HomeBridge lib
    var path = require('path');
    var fs = require('fs');
    var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
    
    // Run HomeBridge
    require(lib + '/cli')();
`

Of course, this was a dirty quick fix, not suitable for updates, but someone out there that are a true programmer might be able to look into the TLS-version problem? What part of homebridge-telldus needs to be updated to use protocol TLSv1.2 to be able to again access Telldus Live under under Node.js v11.4.0 and above?

**Comment by NonjSAme** [comment] 2019-08-16 22:42
Okay... doing some more tests down the road with the assumption that it might have something to do with TLS-versions. I tried to figure out how to start homebridge with the node flag `--tls-min-v1.0` forcing it to accept TLSv1.0 anyway.

Now, node homebirdge is launched from the homebridge shell script at `/usr/local/lib/node_modules/homebridge/bin`. But adding flags to env in a shebang under Linux seems not as easy. At least not under Debian.

Fortunately , I also stumbled across this site [http://sambal.org/2014/02/passing-options-node-shebang-line/](url)

So, by hard coding `/usr/local/lib/node_modules/homebridge/bin/homebridge` to the following, it actually seems to work!!!!

`

    #!/bin/sh
    ":" //# comment; exec /usr/bin/env node --tls-min-v1.0 "$0" "$@"
    
    console.log('javascript');
    
    //
    // This executable sets up the environment and runs the HomeBridge CLI.
    //
    
    'use strict';
    
    process.title = 'homebridge';
    
    // Find the HomeBridge lib
    var path = require('path');
    var fs = require('fs');
    var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');
    
    // Run HomeBridge
    require(lib + '/cli')();
`

Of course, thiw was a dirty quick fix, not suitable for updates, but someone out there that are a true programmer might be able to look into the TLS-version problem?

**Comment by mifi** [comment] 2019-10-13 21:31
EPROTO is fixed now. Closing this. see #76

**Closed by mifi** 2019-10-13 21:31 UTC
